---

- name: Install Podman
  community.general.pacman:
    name: ['podman']
    state: latest
    update_cache: yes

- name: Start and Enable Podman service
  ansible.builtin.systemd:
    name: podman
    state: restarted
    enabled: yes
