---

- name: Shutdown Nomad
  when: install_state == "absent"
  ansible.builtin.systemd:
    name: nomad
    state: stopped
    enabled: false

- name: Remove Nomad service
  when: install_state == "absent"
  file:
    path: "/etc/systemd/system/nomad.service"
    state: absent

- name: Check installed version
  when: install_state != "absent"
  ansible.builtin.command: /usr/bin/nomad version | grep '{{ version }}'
  register: is_same_version_installed
  failed_when: ( is_same_version_installed.rc not in [ 0, 1, 2 ] )

- name: DEBUG Installed version
  when: install_state != "absent"
  ansible.builtin.debug:
    msg: "{{ is_same_version_installed.stdout }}"

- name: Set requires installation fact
  set_fact:
    requires_nomad_installation: "{{ install_state != 'absent' and is_same_version_installed.rc != 0 }}"

- name: Create installer download location /opt/nomadInstall
  when: requires_nomad_installation
  file:
    path: "/opt/nomadInstall"
    state: "directory"

- name: Download Nomad
  become: false
  when: true in installation_required_list
  vars:
    installation_required_list: "{{ ansible_play_hosts|
                                    map('extract', hostvars, 'requires_nomad_installation')|
                                    list }}"
  connection: local
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{version}}/nomad_{{version}}_linux_arm.zip"
    dest: "/tmp/nomad_{{version}}_linux_arm.zip"
    checksum: "sha256:{{shaHash}}"
  run_once: true

- name: Unarchive Nomad
  when: requires_nomad_installation
  ansible.builtin.unarchive:
    src: "/tmp/nomad_{{version}}_linux_arm.zip"
    dest: /opt/nomadInstall

- name: Remove local downloaded archive
  when: requires_nomad_installation
  become: false
  connection: local
  file:
    path: "/tmp/nomad_{{version}}_linux_arm.zip"
    state: absent
  run_once: true

- name: Copy Nomad binary
  when: requires_nomad_installation
  copy:
    src: "/opt/nomadInstall/nomad"
    dest: "/usr/bin/nomad"
    group: root
    owner: root
    remote_src: yes
    mode: 0700

- name: Remove Nomad binary
  when: install_state == "absent"
  file:
    path: "/usr/bin/nomad"
    state: "absent"

- name: Remove installer download location /opt/nomadInstall
  when: install_state == "absent"
  file:
    path: "/opt/nomadInstall"
    state: "absent"

- name: Create data directory /opt/nomad
  when: install_state != "absent"
  file:
    path: "/opt/nomad"
    state: "directory"

- name: Delete data directory /opt/nomad
  when: install_state == "absent"
  file:
    path: "/opt/nomad"
    state: "absent"

- name: Install Nomad Service
  when: install_state != "absent"
  template:
    src: systemd.txt
    dest: /etc/systemd/system/nomad.service
    group: root
    owner: root
    mode: 0644

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Delete /etc/nomad.d
  when: install_state == "absent"
  file:
    path: "/etc/nomad.d"
    state: "absent"

- name: Create /etc/nomad.d
  when: install_state != "absent"
  file:
    path: "/etc/nomad.d"
    state: "directory"

- name: Install nomad.hcl
  when: install_state != "absent"
  template:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
    group: root
    owner: root
    mode: 0700

- name: Install server.hcl
  when: install_state != "absent" and 'nomad_server' in group_names
  template:
    src: server.hcl
    dest: /etc/nomad.d/server.hcl
    group: root
    owner: root
    mode: 0700

- name: Install client.hcl
  when: install_state != "absent" and 'nomad_client' in group_names
  template:
    src: client.hcl
    dest: /etc/nomad.d/client.hcl
    group: root
    owner: root
    mode: 0700

- name: Start and Enable Nomad service
  when: install_state != "absent"
  ansible.builtin.systemd:
    name: nomad
    state: restarted
    enabled: yes
