---

- name: Create mount location
  file:
    path: "{{ gluster_mount_path }}"
    state: "directory"

- name: Mount Gluster volume
  ansible.posix.mount:
    src: "{{ gluster_master }}:{{ gluster_volume_mount }}"
    path: "{{ gluster_mount_path }}"
    opts: defaults,_netdev,backup-volfile-servers={{ gluster_backup_nodes }}
    state: mounted
    fstype: glusterfs
