---

- name: Start and Enable Glusterd service
  ansible.builtin.systemd:
    name: glusterd
    state: started
    enabled: yes

- name: Create trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ gluster_node_ips }}"
  run_once: true

- name: Create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name: "{{ gluster_volume_name }}"
    bricks:  "{{ gluster_brick }}"
    rebalance: yes
    cluster: "{{ gluster_node_ips }}"
    replicas: 2
    options:
      {
        performance.cache-size: 256MB,
        cluster.server-quorum-type: server,
        cluster.self-heal-daemon: enable,
        performance.client-io-threads: "off",
        nfs.disable: "on",
        transport.address-family: inet,
        storage.fips-mode-rchecksum: "on",
        cluster.granular-entry-heal: "on",
        cluster.server-quorum-ratio: 51%
      }
  run_once: true