---

- name: Delete gluster volume
  gluster.gluster.gluster_volume:
    state: absent
    name: "{{ gluster_volume_name }}"

- name: Delete trusted storage pool
  gluster.gluster.gluster_peer:
    state: absent
    nodes: "{{ gluster_node_ips }}"
    force: true

- name: Stop and Disable Glusterd service
  ansible.builtin.systemd:
    name: glusterd
    state: stopped
    enabled: no
