---

- name: Mount Gluster volume
  ansible.posix.mount:
    src: "{{ gluster_master }}:{{ gluster_volume_mount }}"
    path: "{{ gluster_mount_path }}"
    opts: defaults,_netdev
    state: absent
    fstype: glusterfs
