---

- name: Install Consul
  hosts: nomad_server,nomad_client
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - consul
  vars:
    install_state: latest
    version: "1.10.2"
    shaHash: "612c9d1fc32d53a9fa3a911fe79cfd7107832fb0c57dca2a710078b5d7af9759"

- name: Install Nomad
  hosts: nomad_server,nomad_client
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - nomad
  vars:
    install_state: install
    version: "1.1.4"
    shaHash: "3a199b4b1cb10f89cb0ecb814c8a9990d68e2e3bcc0f3c1efdcca36b64d61f7c"
