---
- name: Build x64 Emulator
  hosts: controller[0]
  tasks:
    - remote_user: root
      become: yes
      become_method: sudo
      community.general.pacman:
        name: ['git', 'base-devel', 'cmake']
        state: latest
        update_cache: yes
    - remote_user: root
      become: yes
      become_method: sudo
      file:
        state: directory
        path: "{{ artifact_base_path }}/box64"
        mode: 0777
    - name: clone
      ansible.builtin.git:
        repo: 'https://github.com/ptitSeb/box64.git'
        dest: "{{ artifact_base_path }}/box64"
    - remote_user: root
      become: yes
      become_method: sudo
      file:
        state: directory
        path: "{{ artifact_base_path }}/box64-build"
        mode: 0777
    - name: cmake
      command:
        chdir: "{{ artifact_base_path }}/box64-build"
        cmd: cmake ../box64 -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: make
      shell:
        cmd: make -j$(nproc --ignore=1)
        chdir: "{{ artifact_base_path }}/box64-build"
  run_once: true

- name: Install x64 Emulator
  hosts: controller[0]
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: make
      command:
        chdir: "{{ artifact_base_path }}/box64-build"
        cmd: make install
    - name: Restart binfmt
      ansible.builtin.systemd:
        name: systemd-binfmt
        state: restarted
  run_once: true
