---
- name: Install Dynatrace OneAgent
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  collections:
    - dynatrace.oneagent
  tasks:
    - import_role:
        name: oneagent
  vars:
    oneagent_install_args:
      - --restart-service
      - --set-network-zone='{{ oneagent_network_zone }}'
      - --set-host-group='{{ group_names[0] }}'
  serial: 2
