---
- name: Shutdown Computing
  hosts: "computing:&raspberrypi"
  remote_user: root
  become: yes
  tasks:
    - community.general.shutdown:

- name: Shutdown Controller
  hosts: "controller:&raspberrypi"
  remote_user: root
  become: yes
  tasks:
    - community.general.shutdown:

- name: Shutdown Storage
  hosts: "storage:&raspberrypi"
  remote_user: root
  become: yes
  tasks:
    - community.general.shutdown: