---
- name: Restart service
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: yes

