---
- name: Ensure system configuration
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - sys-setup

- name: Install essential packages 
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo   
  tasks:
    - community.general.pacman:
        name: ['vim', 'zip', 'unzip']
        state: latest
        update_cache: yes
    - name: Start and Enable Podman service
      ansible.builtin.systemd:
        name: podman
        state: restarted
        enabled: yes

- name: Reboot
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - reboot:
 