---
- name: Ensure system configuration
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - sys-setup

- name: Install essential packages
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - community.general.pacman:
        name: ['vim', 'zip', 'unzip', 'wget']
        state: latest
        update_cache: yes

- name: Install essential packages
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - community.general.pacman:
        name: ['brcm-patchram-plus']
        state: absent
        extra_args: --recursive --nosave

- name: Setup Storage
  hosts: storage
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - storage-setup

- name: Reboot
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - reboot:
