---

- name: Upgrade Storage
  hosts: storage
  remote_user: root
  become: yes
  serial: 1 # HA upgrade so GlusterFS stays online
  vars:
    shutdown_glusterd: true
    unlock_vault: false
  roles:
    - sys-upgrade
  post_tasks:
    - name: Start Self-heal
      ansible.builtin.command: "gluster volume heal {{ gluster_volume_name }}"
      run_once: true

- name: Upgrade Computing
  hosts: computing
  remote_user: root
  become: yes
  serial: 2
  vars:
    shutdown_glusterd: false
    unlock_vault: false
  roles:
    - sys-upgrade

- name: Upgrade Controller
  hosts: controller
  remote_user: root
  become: yes
  serial: 1
  vars:
    shutdown_glusterd: true
    unlock_vault: false
  roles:
    - sys-upgrade
