---
- name: Update Packages
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - sys-upgrade
  serial: 6

- name: Reboot
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - reboot:
