---

- name: Stop Runner service
  ignore_errors: yes
  ansible.builtin.systemd:
    name: "{{ systemd_service }}"
    state: stopped
    enabled: no

- name: Configure Runner
  ignore_errors: yes
  ansible.builtin.command: "{{ github_runner_install_location }}/config.sh remove --token '{{ github_runner_access_token }}'"

- name: Remove Systemd service
  file:
    path: "{{ systemd_location }}"
    state: absent

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Remove Runner work directory
  file:
    path: "{{ github_runner_data_dir }}"
    state: "absent"

- name: Remove Runner install directory
  file:
    path: "{{ github_runner_install_location }}"
    state: "absent"

- name: Remove Github group
  ansible.builtin.group:
    name: "{{ group }}"
    system: true
    state: absent

- name: Remove Github user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    system: true
    state: absent
