---

- name: Check installed version
  ansible.builtin.command: /usr/bin/consul version | grep '{{ version }}'
  register: is_same_version_installed
  failed_when: ( is_same_version_installed.rc not in [ 0, 1, 2 ] )

- name: DEBUG Installed version
  ansible.builtin.debug:
    msg: "{{ is_same_version_installed.stdout }}"

- name: Set requires installation fact
  set_fact:
    requires_consul_installation: "{{ is_same_version_installed.rc != 0 }}"

- name: Create installer download location /opt/consulInstall
  when: requires_consul_installation
  file:
    path: "/opt/consulInstall"
    state: "directory"

- name: Download Consul
  become: false
  when: true in installation_required_list
  vars:
    installation_required_list: "{{ ansible_play_hosts|
                                    map('extract', hostvars, 'requires_consul_installation')|
                                    list }}"
  connection: local
  get_url:
    url: "https://releases.hashicorp.com/consul/{{version}}/consul_{{version}}_linux_arm64.zip"
    dest: "/tmp/consul_{{version}}_linux_arm64.zip"
    checksum: "sha256:{{shaHash}}"
  run_once: true

- name: Unarchive Consul
  when: requires_consul_installation
  ansible.builtin.unarchive:
    src: "/tmp/consul_{{version}}_linux_arm64.zip"
    dest: /opt/consulInstall

- name: Remove local downloaded archive
  when: requires_consul_installation
  become: false
  connection: local
  file:
    path: "/tmp/consul_{{version}}_linux_arm64.zip"
    state: absent
  run_once: true

- name: Add consul group
  ansible.builtin.group:
    name: consul
    system: true
    state: present

- name: Add consul user
  ansible.builtin.user:
    name: consul
    group: consul
    system: true
    state: present

- name: Copy Consul binary
  when: requires_consul_installation
  copy:
    src: "/opt/consulInstall/consul"
    dest: "/usr/bin/consul"
    group: consul
    owner: consul
    remote_src: yes
    mode: 0700

- name: Create data directory /opt/consul
  file:
    path: "/opt/consul"
    state: "directory"
    owner: consul
    group: consul

- name: Install Consul Service
  template:
    src: systemd.txt
    dest: /etc/systemd/system/consul.service
    group: root
    owner: root
    mode: 0644

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Create /etc/consul.d
  file:
    path: "/etc/consul.d"
    state: "directory"

- name: Install consul.hcl
  template:
    src: consul.hcl
    dest: /etc/consul.d/consul.hcl
    group: consul
    owner: consul
    mode: 0700

- name: Install server.hcl
  when: "'nomad_server' in group_names"
  template:
    src: server.hcl
    dest: /etc/consul.d/server.hcl
    group: consul
    owner: consul
    mode: 0640

- name: Install client.hcl
  when: "'nomad_client' in group_names"
  template:
    src: client.hcl
    dest: /etc/consul.d/client.hcl
    group: consul
    owner: consul
    mode: 0640

- name: Start and Enable Consul service
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: yes
