---

- name: Fetch installed version
  ansible.builtin.command: /usr/bin/vault version
  register: installed_version_out
  failed_when: ( installed_version_out.rc not in [ 0, 1, 2 ] )

- name: DEBUG Installed version
  ansible.builtin.debug:
    msg: "{{ installed_version_out.stdout }}"

- name: Set requires installation fact
  set_fact:
    requires_vault_installation: "{{ installed_version_out.rc != 0 or version not in installed_version_out.stdout}}"
    architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

- name: DEBUG Installation required?
  ansible.builtin.debug:
    msg: "{{ requires_vault_installation }}"

- name: Create installer download location /opt/vaultInstall
  when: requires_vault_installation
  file:
    path: "/opt/vaultInstall"
    state: "directory"

- name: Download Vault
  when: true in installation_required_list
  vars:
    installation_required_list: "{{ ansible_play_hosts|
                                    map('extract', hostvars, 'requires_vault_installation')|
                                    list }}"
  get_url:
    url: "https://releases.hashicorp.com/vault/{{version}}/vault_{{version}}_linux_arm64.zip"
    dest: "/tmp/vault_{{version}}_linux_arm64.zip"
    checksum: "sha256:https://releases.hashicorp.com/vault/{{version}}/vault_{{version}}_SHA256SUMS"

- name: Unarchive Vault
  when: requires_vault_installation
  ansible.builtin.unarchive:
    src: "/tmp/vault_{{version}}_linux_arm64.zip"
    remote_src: true
    dest: /opt/vaultInstall

- name: Remove local downloaded archive
  when: requires_vault_installation
  file:
    path: "/tmp/vault_{{version}}_linux_arm64.zip"
    state: absent

- name: Add vault group
  ansible.builtin.group:
    name: vault
    system: true
    state: present

- name: Add vault user
  ansible.builtin.user:
    name: vault
    group: vault
    system: true
    state: present

- name: Copy Vault binary
  when: requires_vault_installation
  copy:
    src: "/opt/vaultInstall/vault"
    dest: "/usr/bin/vault"
    group: vault
    owner: vault
    remote_src: yes
    mode: 0700

- name: Install Vault Service
  template:
    src: systemd.txt
    dest: /etc/systemd/system/vault.service
    group: root
    owner: root
    mode: 0644

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Create /etc/vault.d
  file:
    path: "/etc/vault.d"
    state: "directory"

- name: Install vault.hcl
  template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl
    group: vault
    owner: vault
    mode: 0600

- name: Start and Enable Vault service
  ansible.builtin.systemd:
    name: vault
    state: restarted
    enabled: yes

- name: Ensure Vault is in a running state
  service:
    name: vault
    state: started
  register: vaultDetails
  until: vaultDetails.status.ActiveState == "active"
  retries: 15
  delay: 20

- name: Unseal Vault
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
    VAULT_UNSEAL_KEY:  "{{ vault_unseal_key }}"
  shell: vault operator unseal ${VAULT_UNSEAL_KEY}
