---

- name: Install Docker
  community.general.pacman:
    name: ['docker', 'cni-plugins', 'community/docker-buildx']
    state: latest
    update_cache: yes

- name: Ensure Docker directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory

- name: Install daemon.json
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    group: root
    owner: root
    mode: 0644

- name: Cleanup failed systemd service
  command:
    cmd: systemctl reset-failed docker
  ignore_errors: yes

- name: Start and Enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: yes
  when: restart_docker