---
# Is there a way to check for plugin versions in nomad?
#- name: Check installed version
#  ansible.builtin.command: "echo 'derp' | grep '{{ podman_driver_version }}'"
#  register: is_same_podman_driver_version_installed
#  failed_when: ( is_same_podman_driver_version_installed.rc not in [ 0, 1, 2 ] )

#- name: DEBUG Installed version
#  ansible.builtin.debug:
#    msg: "{{ is_same_podman_driver_version_installed.stdout }}"

- name: Set requires installation fact
  set_fact:

    #requires_podman_driver_installation: "{{ is_same_podman_driver_version_installed.rc != 0 }}"
    requires_podman_driver_installation: true

- name: Create installer download location /opt/podmanDriverInstall
  when: requires_podman_driver_installation
  file:
    path: "/opt/podmanDriverInstall"
    state: "directory"

- name: Download Podman Driver
  become: false
  when: true in installation_required_list
  vars:
    installation_required_list: "{{ ansible_play_hosts|
                                    map('extract', hostvars, 'requires_podman_driver_installation')|
                                    list }}"
  connection: local
  get_url:
    url: "https://releases.hashicorp.com/nomad-driver-podman/{{ podman_driver_version }}/nomad-driver-podman_{{ podman_driver_version }}_linux_arm64.zip"
    dest: "/tmp/nomad-driver-podman_{{ podman_driver_version }}_linux_arm64.zip"
    checksum: "sha256:{{ podman_driver_hash }}"
  run_once: true

- name: Unarchive Podman Driver
  when: requires_podman_driver_installation
  ansible.builtin.unarchive:
    src: "/tmp/nomad-driver-podman_{{ podman_driver_version }}_linux_arm64.zip"
    dest: /opt/podmanDriverInstall

- name: Remove local downloaded archive
  when: requires_podman_driver_installation
  become: false
  connection: local
  file:
    path: "/tmp/nomad-driver-podman_{{version}}_linux_arm64.zip"
    state: absent
  run_once: true

- name: Copy Podman Driver binary
  when: requires_podman_driver_installation
  copy:
    src: "/opt/podmanDriverInstall/nomad-driver-podman"
    dest: "/opt/nomad/plugins/nomad-driver-podman"
    group: root
    owner: root
    remote_src: yes
    mode: 0700
