---

- include_tasks: install_docker.yml
  when: install_state != "absent"

- include_tasks: install_nomad.yml
  when: install_state != "absent"

- include_tasks: start_nomad.yml
  when: install_state != "absent"

- include_tasks: uninstall_nomad.yml
  when: install_state == "absent"

- include_tasks: uninstall_docker.yml
  when: install_state == "absent"
