---

- name: Shutdown Nomad
  ansible.builtin.systemd:
    name: nomad
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Remove Nomad service
  file:
    path: "/etc/systemd/system/nomad.service"
    state: absent

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Remove Nomad binary
  file:
    path: "/usr/bin/nomad"
    state: "absent"

- name: Remove installer download location /opt/nomadInstall
  file:
    path: "/opt/nomadInstall"
    state: "absent"

- name: Delete data directory
  file:
    path: "{{ nomad_data_dir }}"
    state: "absent"
  when: delete_data

- name: Delete host volume directories
  file:
    path: "{{ item.path }}"
    state: "absent"
  loop: "{{ nomad_host_volumes }}"
  when: delete_data

- name: Delete shared data directory
  file:
    path: "{{ nomad_shared_dir }}"
    state: "absent"
  when: delete_data

- name: Delete /etc/nomad.d
  file:
    path: "/etc/nomad.d"
    state: "absent"

- name: Cleanup failed systemd service
  command:
    cmd: systemctl reset-failed nomad
  ignore_errors: yes
