---

- name: Stop and Disable Docker service
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Uninstall Docker
  community.general.pacman:
    name: ['docker']
    state: absent
    extra_args: --recursive --nosave
