---

- name: Stop and Disable Docker service
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Uninstall daemon.json
  file:
    path: /etc/docker/daemon.json
    state: absent

- name: Uninstall Docker
  community.general.pacman:
    name: ['docker', 'cni-plugins']
    state: absent
    extra_args: --recursive --nosave

- name: Cleanup failed systemd service
  command:
    cmd: systemctl reset-failed docker
  ignore_errors: yes
