---

- name: Uninstall Github Runner
  hosts: computing
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - github-runner
  vars:
    install_state: absent

- name: Uninstall Nomad
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - nomad
  vars:
    install_state: absent

- name: Uninstall Vault
  hosts: controller
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - vault
  vars:
    install_state: absent

- name: Uninstall Consul
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - consul
  vars:
    install_state: absent

- name: Uninstall Gluster Clients
  hosts: all:!storage
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - glusterfs
  vars:
    install_type: client
    install_state: absent