---
- name: Install Gluster Server
  hosts: storage
  remote_user: root
  become: yes
  roles:
    - glusterfs
  vars:
    install_type: cluster
    install_state: present

- name: Install Gluster Clients
  hosts: controller,computing
  remote_user: root
  become: yes
  roles:
    - glusterfs
  vars:
    install_type: client
    install_state: present
