---

- name: Install Consul
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - consul
  vars:
    install_state: latest
    version: "{{ consul_version }}"
    shaHash: "{{ consul_version_hash }}"
