---

- name: Install Vault
  hosts: controller
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - vault
  vars:
    install_state: latest
    version: "1.8.3"
    shaHash: "c783b6fa65008e01f64fdedc26658624ef19c84f9d08c32a19d6e2770dd937fd"
